/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 *//*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import dao.Lecturer;
import db.DBconnect;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author acer
 */
public class LecturersPage extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1t
     *
     */
    PreparedStatement pst;
    Lecturer lecturer = new Lecturer();
    DBconnect myConnection = new DBconnect();
    
    public LecturersPage() {
        initComponents();
        View_Lecturers.setVisible(false);
        LecturerMenu.setVisible(true);
       // Add_Lecturer.setVisible(false);
        
        Lecturers_table.setModel(new DefaultTableModel(null, new Object[]{"name","employee_id","faculty","department","center","building","level","rank"}));
        //populate the jtable
        lecturer.fillLecturersJTable1(Lecturers_table);
        
        Lecturers_table1.setModel(new DefaultTableModel(null, new Object[]{"name","employee_id","faculty","department","center","building","level","rank"}));
        //populate the jtable
        lecturer.fillLecturersJTable1(Lecturers_table1);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        ADD_BUTTON = new javax.swing.JButton();
        REMOVE_BUTTON = new javax.swing.JButton();
        VIEW_BUTTON = new javax.swing.JButton();
        NOT_AVAILABLE_TIME_BUTTON = new javax.swing.JButton();
        EDIT_BUTTON = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        LecturerMenu = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldID_Name = new javax.swing.JTextField();
        EmployeeID = new javax.swing.JLabel();
        jTextFieldID1_EmployeeID = new javax.swing.JTextField();
        Faculty = new javax.swing.JLabel();
        Department = new javax.swing.JLabel();
        Center = new javax.swing.JLabel();
        Building = new javax.swing.JLabel();
        Level = new javax.swing.JLabel();
        jTextFieldID7_Rank = new javax.swing.JTextField();
        Rank = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        CLEARFEILDS_BUTTON = new javax.swing.JButton();
        jComboBox1_faculty = new javax.swing.JComboBox();
        jComboBox2_department = new javax.swing.JComboBox();
        jComboBox3_center = new javax.swing.JComboBox();
        jComboBox4_building = new javax.swing.JComboBox();
        jComboBox5_level = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1_Search = new javax.swing.JTextField();
        SEARCH_BUTTON = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Lecturers_table = new javax.swing.JTable();
        REFRESH_BUTTON = new javax.swing.JButton();
        View_Lecturers = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1_Search1 = new javax.swing.JTextField();
        SEARCH_BUTTON1 = new javax.swing.JButton();
        REFRESH_BUTTON1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Lecturers_table1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton1.setBackground(new java.awt.Color(51, 0, 51));
        jButton1.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 55, 100, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/header_image.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 1250, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(280, 511));

        ADD_BUTTON.setBackground(new java.awt.Color(51, 153, 255));
        ADD_BUTTON.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ADD_BUTTON.setText("ADD LECTURER");
        ADD_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD_BUTTONActionPerformed(evt);
            }
        });

        REMOVE_BUTTON.setBackground(new java.awt.Color(51, 153, 255));
        REMOVE_BUTTON.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        REMOVE_BUTTON.setText("REMOVE LECTURER");
        REMOVE_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REMOVE_BUTTONActionPerformed(evt);
            }
        });

        VIEW_BUTTON.setBackground(new java.awt.Color(51, 153, 255));
        VIEW_BUTTON.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        VIEW_BUTTON.setText("VIEW LECTURER");
        VIEW_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VIEW_BUTTONActionPerformed(evt);
            }
        });

        NOT_AVAILABLE_TIME_BUTTON.setBackground(new java.awt.Color(51, 153, 255));
        NOT_AVAILABLE_TIME_BUTTON.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NOT_AVAILABLE_TIME_BUTTON.setText("NOT AVAILABLE TIME");
        NOT_AVAILABLE_TIME_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NOT_AVAILABLE_TIME_BUTTONActionPerformed(evt);
            }
        });

        EDIT_BUTTON.setBackground(new java.awt.Color(51, 153, 255));
        EDIT_BUTTON.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EDIT_BUTTON.setText("EDIT LECTURERS");
        EDIT_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDIT_BUTTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(NOT_AVAILABLE_TIME_BUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                    .addComponent(VIEW_BUTTON, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(REMOVE_BUTTON, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                    .addComponent(EDIT_BUTTON, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ADD_BUTTON, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(ADD_BUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(EDIT_BUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(REMOVE_BUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(VIEW_BUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addComponent(NOT_AVAILABLE_TIME_BUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        jPanel11.setBackground(new java.awt.Color(51, 255, 255));
        jPanel11.setLayout(new javax.swing.OverlayLayout(jPanel11));

        LecturerMenu.setBackground(new java.awt.Color(0, 0, 51));

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));

        jPanel7.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lecturer Details");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jTextFieldID_Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldID_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldID_NameActionPerformed(evt);
            }
        });

        EmployeeID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EmployeeID.setText("Employee ID :");
        EmployeeID.setToolTipText("");

        jTextFieldID1_EmployeeID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldID1_EmployeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldID1_EmployeeIDActionPerformed(evt);
            }
        });

        Faculty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Faculty.setText("Faculty :");
        Faculty.setToolTipText("");

        Department.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Department.setText("Department :");
        Department.setToolTipText("");

        Center.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Center.setText("Center :");
        Center.setToolTipText("");

        Building.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Building.setText("Building :");
        Building.setToolTipText("");

        Level.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Level.setText("Level :");
        Level.setToolTipText("");

        jTextFieldID7_Rank.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldID7_Rank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldID7_RankActionPerformed(evt);
            }
        });

        Rank.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Rank.setText("Rank :");
        Rank.setToolTipText("");

        Name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Name.setText("Name :");
        Name.setToolTipText("");

        CLEARFEILDS_BUTTON.setBackground(new java.awt.Color(51, 153, 255));
        CLEARFEILDS_BUTTON.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CLEARFEILDS_BUTTON.setText("Clear Feilds");
        CLEARFEILDS_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARFEILDS_BUTTONActionPerformed(evt);
            }
        });

        jComboBox1_faculty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1_faculty.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Faculty", "Computing", "Engineering", "Business", "Humanities & Science" }));

        jComboBox2_department.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox2_department.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Department", "Software Engineering", "Computer System Network", "Information Technology. Civil Engineering", "Electronic Engineering", "Material Engineering", "" }));

        jComboBox3_center.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox3_center.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Center", "Malabe", "Metro", "Matara", "Kandy" }));

        jComboBox4_building.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox4_building.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Building", "A-Block", "B-Block", "C-Block", "D-Block", "E-Block" }));

        jComboBox5_level.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox5_level.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Level", "1", "2", "3", "4", "5", "6", "7" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EmployeeID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Faculty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Department, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Center, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Building, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Level, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Rank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldID1_EmployeeID, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldID_Name)
                            .addComponent(CLEARFEILDS_BUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1_faculty, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox2_department, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox3_center, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox4_building, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox5_level, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldID7_Rank, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(16, 16, 16))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jTextFieldID_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jTextFieldID1_EmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Faculty, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1_faculty, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Department, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2_department, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Center, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3_center, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Building, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4_building, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Level, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox5_level, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldID7_Rank, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Rank, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(CLEARFEILDS_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));

        jPanel9.setBackground(new java.awt.Color(0, 0, 51));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Current Lecturers");

        jTextField1_Search.setPreferredSize(new java.awt.Dimension(69, 30));

        SEARCH_BUTTON.setText("Search");
        SEARCH_BUTTON.setPreferredSize(new java.awt.Dimension(73, 30));
        SEARCH_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCH_BUTTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jTextField1_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SEARCH_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1_Search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SEARCH_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Lecturers_table.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lecturers_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "EmployeeID", "Faculty", "Department", "Center", "Building", "Level", "Rank"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Lecturers_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lecturers_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Lecturers_table);

        REFRESH_BUTTON.setBackground(new java.awt.Color(51, 153, 255));
        REFRESH_BUTTON.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        REFRESH_BUTTON.setText("Refresh");
        REFRESH_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REFRESH_BUTTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(REFRESH_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(REFRESH_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout LecturerMenuLayout = new javax.swing.GroupLayout(LecturerMenu);
        LecturerMenu.setLayout(LecturerMenuLayout);
        LecturerMenuLayout.setHorizontalGroup(
            LecturerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LecturerMenuLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LecturerMenuLayout.setVerticalGroup(
            LecturerMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel11.add(LecturerMenu);

        View_Lecturers.setBackground(new java.awt.Color(204, 204, 255));

        jPanel10.setBackground(new java.awt.Color(0, 0, 51));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Current Lecturers");

        jTextField1_Search1.setPreferredSize(new java.awt.Dimension(69, 30));

        SEARCH_BUTTON1.setText("Search");
        SEARCH_BUTTON1.setPreferredSize(new java.awt.Dimension(73, 30));
        SEARCH_BUTTON1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCH_BUTTON1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 466, Short.MAX_VALUE)
                .addComponent(jTextField1_Search1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SEARCH_BUTTON1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1_Search1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SEARCH_BUTTON1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        REFRESH_BUTTON1.setBackground(new java.awt.Color(51, 153, 255));
        REFRESH_BUTTON1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        REFRESH_BUTTON1.setText("Refresh");
        REFRESH_BUTTON1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REFRESH_BUTTON1ActionPerformed(evt);
            }
        });

        Lecturers_table1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Lecturers_table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lecturers_table1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Lecturers_table1);

        jButton2.setBackground(new java.awt.Color(51, 0, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Lecturers Menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout View_LecturersLayout = new javax.swing.GroupLayout(View_Lecturers);
        View_Lecturers.setLayout(View_LecturersLayout);
        View_LecturersLayout.setHorizontalGroup(
            View_LecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, View_LecturersLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(View_LecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(View_LecturersLayout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(REFRESH_BUTTON1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(16, 16, 16))
        );
        View_LecturersLayout.setVerticalGroup(
            View_LecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(View_LecturersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(View_LecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(REFRESH_BUTTON1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel11.add(View_Lecturers);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ADD_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD_BUTTONActionPerformed

        Add_Lecture_Form  add_lecturer =  new Add_Lecture_Form(); 
        add_lecturer.setVisible(true);
        add_lecturer.pack();
        add_lecturer.setLocationRelativeTo(null);
        add_lecturer.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        //Add_Lecturer.setVisible(true);

    }//GEN-LAST:event_ADD_BUTTONActionPerformed

    private void REMOVE_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REMOVE_BUTTONActionPerformed
        
       if(jTextFieldID_Name.getText().trim().equals("") || jTextFieldID1_EmployeeID.getText().trim().equals("") || jTextFieldID7_Rank.getText().trim().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Some Fields are empty", "Empty Field", JOptionPane.WARNING_MESSAGE);
       }
       else if(jComboBox1_faculty.getSelectedItem().equals("Select Faculty") || jComboBox2_department.getSelectedItem().equals("Select Department") || jComboBox3_center.getSelectedItem().equals("Select Center")
                || jComboBox4_building.getSelectedItem().equals("Select Building") || jComboBox5_level.getSelectedItem().equals("Select Level")){
            JOptionPane.showMessageDialog(rootPane, "Some Feilds Are Not Selected", "Fill Details Error", JOptionPane.ERROR_MESSAGE);
        }
       else{   
     // delete the selected clients
        try{
            String employee_id = String.valueOf(jTextFieldID1_EmployeeID.getText());
            String name = String.valueOf(jTextFieldID_Name.getText());
            String faculty = String.valueOf(jComboBox1_faculty.getSelectedItem());
            String department = String.valueOf(jComboBox2_department.getSelectedItem());
            String center = String.valueOf(jComboBox3_center.getSelectedItem());
            String building = String.valueOf(jComboBox4_building.getSelectedItem());
            String level = String.valueOf(jComboBox5_level.getSelectedItem());
            String rank = String.valueOf(jTextFieldID7_Rank.getText());

            if(lecturer.removeLecturer(employee_id)){
               JOptionPane.showMessageDialog(rootPane, "Lecturer Deleted Successfully", "Remove Lecturer", JOptionPane.INFORMATION_MESSAGE);  
            }else{
                JOptionPane.showMessageDialog(rootPane, "Lecturer Not Deleted", "Remove Lecturer Error", JOptionPane.ERROR_MESSAGE);
            }
         }catch(HeadlessException | NumberFormatException ex){
             
         } 
       }
         Lecturers_table.setModel(new DefaultTableModel(null, new Object[]{"name","employee_id","faculty","department","center","building","level","rank"}));
        //populate the jtable
         lecturer.fillLecturersJTable1(Lecturers_table);
         
         Lecturers_table1.setModel(new DefaultTableModel(null, new Object[]{"name","employee_id","faculty","department","center","building","level","rank"}));
        //populate the jtable
         lecturer.fillLecturersJTable1(Lecturers_table1);
         
        jTextFieldID_Name.setText(" ");
        jTextFieldID1_EmployeeID.setText(" ");
        jComboBox1_faculty.setSelectedItem("Select Faculty");
        jComboBox2_department.setSelectedItem("Select Department");
        jComboBox3_center.setSelectedItem("Select Center");
        jComboBox4_building.setSelectedItem("Select Building");
        jComboBox5_level.setSelectedItem("Select Level");
        jTextFieldID7_Rank.setText(" ");
    }//GEN-LAST:event_REMOVE_BUTTONActionPerformed

    private void VIEW_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VIEW_BUTTONActionPerformed
        // TODO add your handling code here:
        View_Lecturers.setVisible(true);
        LecturerMenu.setVisible(false);
       // Add_Lecturer.setVisible(false);
                
    }//GEN-LAST:event_VIEW_BUTTONActionPerformed

    private void NOT_AVAILABLE_TIME_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NOT_AVAILABLE_TIME_BUTTONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NOT_AVAILABLE_TIME_BUTTONActionPerformed

    private void EDIT_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDIT_BUTTONActionPerformed

        String employeeID = jTextFieldID1_EmployeeID.getText();
        String name = jTextFieldID_Name.getText();
        String faculty = jComboBox1_faculty.getSelectedItem().toString();
        String department = jComboBox2_department.getSelectedItem().toString();
        String center = jComboBox3_center.getSelectedItem().toString();
        String building = jComboBox4_building.getSelectedItem().toString();
        String level = jComboBox5_level.getSelectedItem().toString();
        String rank = jComboBox5_level.getSelectedItem().toString()+"."+jTextFieldID1_EmployeeID.getText();

        if(name.trim().equals("") || faculty.trim().equals("Select Faculty") || department.trim().equals("Select Department") || center.trim().equals("Select Center") 
                || building.trim().equals("Select Building") || level.trim().equals("Select Level") || rank.trim().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Some fields are empty", "Empty Field", JOptionPane.WARNING_MESSAGE);
        }
        
        else if(!(Pattern.matches("^[0-9]{6}+$",jTextFieldID1_EmployeeID.getText()))){
            JOptionPane.showMessageDialog(rootPane, "Please enter valid Employee ID", "Fill Details Error", JOptionPane.ERROR_MESSAGE);
        }
       
        else{
            try{
                employeeID = String.valueOf(jTextFieldID1_EmployeeID.getText());

                if(lecturer.editLecturer(employeeID,name,faculty,department,center,building,level,rank)){
                    JOptionPane.showMessageDialog(rootPane, "Lecturer Data Updated Successfully", "Edit Lecturer", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Lecturer Data Not Updated", "Edit Lecturer Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(rootPane, ex.getMessage() + " - Enter The Lecturer Id(number)", "Lecturer ID Error", JOptionPane.ERROR_MESSAGE);
            }
         }  
        
        //clear the jtable first
        Lecturers_table.setModel(new DefaultTableModel(null, new Object[]{"name","employee_id","faculty","department","center","building","level","rank"}));
        //populate the jtable
        lecturer.fillLecturersJTable1(Lecturers_table);
        
        Lecturers_table1.setModel(new DefaultTableModel(null, new Object[]{"name","employee_id","faculty","department","center","building","level","rank"}));
        //populate the jtable
        lecturer.fillLecturersJTable1(Lecturers_table1);
        
        jTextFieldID_Name.setText(" ");
        jTextFieldID1_EmployeeID.setText(" ");
        jComboBox1_faculty.setSelectedItem("Select Faculty");
        jComboBox2_department.setSelectedItem("Select Department");
        jComboBox3_center.setSelectedItem("Select Center");
        jComboBox4_building.setSelectedItem("Select Building");
        jComboBox5_level.setSelectedItem("Select Level");
        jTextFieldID7_Rank.setText(" ");
        
    }//GEN-LAST:event_EDIT_BUTTONActionPerformed

    private void jTextFieldID7_RankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldID7_RankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldID7_RankActionPerformed

    private void jTextFieldID1_EmployeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldID1_EmployeeIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldID1_EmployeeIDActionPerformed

    private void jTextFieldID_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldID_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldID_NameActionPerformed

    private void REFRESH_BUTTON1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REFRESH_BUTTON1ActionPerformed
        
        //clear the jtable first
        Lecturers_table1.setModel(new DefaultTableModel(null, new Object[]{"name","employee_id","faculty","department","center","building","level","rank"}));
        //populate the jtable
        lecturer.fillLecturersJTable1(Lecturers_table1);
    }//GEN-LAST:event_REFRESH_BUTTON1ActionPerformed

    private void Lecturers_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lecturers_tableMouseClicked
        
        //display the selected row data in the jtextfield
        //get the jtable model
        DefaultTableModel model = (DefaultTableModel) Lecturers_table.getModel();      
        //get the selected row index
        int rIndex = Lecturers_table.getSelectedRow();
        //display data
        jTextFieldID_Name.setText(model.getValueAt(rIndex, 0).toString());
        jTextFieldID1_EmployeeID.setText(model.getValueAt(rIndex, 1).toString());
        jComboBox1_faculty.setSelectedItem(model.getValueAt(rIndex, 2).toString());
        jComboBox2_department.setSelectedItem(model.getValueAt(rIndex, 3).toString());
        jComboBox3_center.setSelectedItem(model.getValueAt(rIndex, 4).toString());
        jComboBox4_building.setSelectedItem(model.getValueAt(rIndex, 5).toString());
        jComboBox5_level.setSelectedItem(model.getValueAt(rIndex, 6).toString());
        jTextFieldID7_Rank.setText(model.getValueAt(rIndex, 7).toString());
        
    }//GEN-LAST:event_Lecturers_tableMouseClicked

    private void CLEARFEILDS_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARFEILDS_BUTTONActionPerformed
        
        jTextFieldID_Name.setText(" ");
        jTextFieldID1_EmployeeID.setText(" ");
        jComboBox1_faculty.setSelectedItem("Select Faculty");
        jComboBox2_department.setSelectedItem("Select Department");
        jComboBox3_center.setSelectedItem("Select Center");
        jComboBox4_building.setSelectedItem("Select Building");
        jComboBox5_level.setSelectedItem("Select Level");
        jTextFieldID7_Rank.setText(" ");
    }//GEN-LAST:event_CLEARFEILDS_BUTTONActionPerformed

    private void REFRESH_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REFRESH_BUTTONActionPerformed
       
        //clear the jtable first
        Lecturers_table.setModel(new DefaultTableModel(null, new Object[]{"name","employee_id","faculty","department","center","building","level","rank"}));
        //populate the jtable
        lecturer.fillLecturersJTable1(Lecturers_table);
    }//GEN-LAST:event_REFRESH_BUTTONActionPerformed

    private void SEARCH_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCH_BUTTONActionPerformed
        
        String name = jTextField1_Search.getText();
        String sql = "SELECT `name`, `employee_id`, `faculty`, `department`, `center`, `building`, `level`, `rank` FROM `lecturers` WHERE `name` LIKE '%" + name + "%'";

        try {
            PreparedStatement pst;
            ResultSet rs;
            pst = myConnection.createConnection().prepareStatement(sql);
            rs = pst.executeQuery();
            
        Lecturers_table.setModel(DbUtils.resultSetToTableModel(rs));   
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage() , "Search Details", JOptionPane.ERROR_MESSAGE);
        }
        
        jTextField1_Search.setText(" ");
    }//GEN-LAST:event_SEARCH_BUTTONActionPerformed

    private void SEARCH_BUTTON1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCH_BUTTON1ActionPerformed
        
        
        String name = jTextField1_Search1.getText();
        String sql = "SELECT `name`, `employee_id`, `faculty`, `department`, `center`, `building`, `level`, `rank` FROM `lecturers` WHERE `name` LIKE '%" + name + "%'";

        try {
            PreparedStatement pst;
            ResultSet rs;
            pst = myConnection.createConnection().prepareStatement(sql);
            rs = pst.executeQuery();
            
        Lecturers_table1.setModel(DbUtils.resultSetToTableModel(rs));   
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage() , "Search Details", JOptionPane.ERROR_MESSAGE);
        }
        
        jTextField1_Search1.setText(" ");
    }//GEN-LAST:event_SEARCH_BUTTON1ActionPerformed

    private void Lecturers_table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lecturers_table1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Lecturers_table1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        HomePage home = new HomePage();
        home.setVisible(true);
        home.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         View_Lecturers.setVisible(false);
        LecturerMenu.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LecturersPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LecturersPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LecturersPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LecturersPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LecturersPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD_BUTTON;
    private javax.swing.JLabel Building;
    private javax.swing.JButton CLEARFEILDS_BUTTON;
    private javax.swing.JLabel Center;
    private javax.swing.JLabel Department;
    private javax.swing.JButton EDIT_BUTTON;
    private javax.swing.JLabel EmployeeID;
    private javax.swing.JLabel Faculty;
    private javax.swing.JPanel LecturerMenu;
    private javax.swing.JTable Lecturers_table;
    private javax.swing.JTable Lecturers_table1;
    private javax.swing.JLabel Level;
    private javax.swing.JButton NOT_AVAILABLE_TIME_BUTTON;
    private javax.swing.JLabel Name;
    private javax.swing.JButton REFRESH_BUTTON;
    private javax.swing.JButton REFRESH_BUTTON1;
    private javax.swing.JButton REMOVE_BUTTON;
    private javax.swing.JLabel Rank;
    private javax.swing.JButton SEARCH_BUTTON;
    private javax.swing.JButton SEARCH_BUTTON1;
    private javax.swing.JButton VIEW_BUTTON;
    private javax.swing.JPanel View_Lecturers;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1_faculty;
    private javax.swing.JComboBox jComboBox2_department;
    private javax.swing.JComboBox jComboBox3_center;
    private javax.swing.JComboBox jComboBox4_building;
    private javax.swing.JComboBox jComboBox5_level;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1_Search;
    private javax.swing.JTextField jTextField1_Search1;
    private javax.swing.JTextField jTextFieldID1_EmployeeID;
    private javax.swing.JTextField jTextFieldID7_Rank;
    private javax.swing.JTextField jTextFieldID_Name;
    // End of variables declaration//GEN-END:variables
}
