/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 *//*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import dao.Lecturer;
import dao.Subject;
import db.DBconnect;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author acer
 */
public class SubjectPage extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1t
     */
    
    PreparedStatement pst;
    Subject subject = new Subject();
    DBconnect myConnection = new DBconnect();
    
    public SubjectPage() {
        initComponents();
        View_Subjects.setVisible(false);
        SubjectMenu.setVisible(true);
       // Add_Lecturer.setVisible(false);
        
        Subjects_table.setModel(new DefaultTableModel(null, new Object[]{"offered_year","offered_semester","subject_name","subject_code","no_lec_hours","no_tute_hours","no_lab_hours","no_evaluation_hours"}));
        //populate the jtable
        subject.fillSubjectJTable1(Subjects_table);
        
        Subjects_table1.setModel(new DefaultTableModel(null, new Object[]{"offered_year","offered_semester","subject_name","subject_code","no_lec_hours","no_tute_hours","no_lab_hours","no_evaluation_hours"}));
       //populate the jtable
        subject.fillSubjectJTable1(Subjects_table1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        ADD_BUTTON = new javax.swing.JButton();
        REMOVE_BUTTON = new javax.swing.JButton();
        VIEW_BUTTON = new javax.swing.JButton();
        EDIT_BUTTON = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        SubjectMenu = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        EmployeeID = new javax.swing.JLabel();
        Faculty = new javax.swing.JLabel();
        jTextFieldID2_Name = new javax.swing.JTextField();
        Department = new javax.swing.JLabel();
        jTextFieldID3_Code = new javax.swing.JTextField();
        Center = new javax.swing.JLabel();
        jTextFieldID4_Lec_Hours = new javax.swing.JTextField();
        Building = new javax.swing.JLabel();
        jTextFieldID5_Tute_Hours = new javax.swing.JTextField();
        Level = new javax.swing.JLabel();
        jTextFieldID6_Lab_Hours = new javax.swing.JTextField();
        jTextFieldID7_Evaluation_Hours = new javax.swing.JTextField();
        Rank = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        CLEARFEILDS_BUTTON = new javax.swing.JButton();
        jComboBox1_offered_year = new javax.swing.JComboBox();
        jComboBox2_offered_semester = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1_Search = new javax.swing.JTextField();
        SEARCH_BUTTON = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Subjects_table = new javax.swing.JTable();
        REFRESH_BUTTON = new javax.swing.JButton();
        View_Subjects = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1_Search1 = new javax.swing.JTextField();
        SEARCH_BUTTON1 = new javax.swing.JButton();
        REFRESH_BUTTON1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Subjects_table1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton1.setBackground(new java.awt.Color(51, 0, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Home");
        jButton1.setMaximumSize(new java.awt.Dimension(85, 31));
        jButton1.setMinimumSize(new java.awt.Dimension(85, 31));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 100, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/header_image.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 0, 1250, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(280, 511));

        ADD_BUTTON.setBackground(new java.awt.Color(51, 153, 255));
        ADD_BUTTON.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ADD_BUTTON.setText("ADD SUBJECT");
        ADD_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD_BUTTONActionPerformed(evt);
            }
        });

        REMOVE_BUTTON.setBackground(new java.awt.Color(51, 153, 255));
        REMOVE_BUTTON.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        REMOVE_BUTTON.setText("REMOVE SUBJECTS");
        REMOVE_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REMOVE_BUTTONActionPerformed(evt);
            }
        });

        VIEW_BUTTON.setBackground(new java.awt.Color(51, 153, 255));
        VIEW_BUTTON.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        VIEW_BUTTON.setText("VIEW SUBJECTS");
        VIEW_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VIEW_BUTTONActionPerformed(evt);
            }
        });

        EDIT_BUTTON.setBackground(new java.awt.Color(51, 153, 255));
        EDIT_BUTTON.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EDIT_BUTTON.setText("EDIT SUBJECTS");
        EDIT_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDIT_BUTTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ADD_BUTTON, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EDIT_BUTTON, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(REMOVE_BUTTON, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VIEW_BUTTON, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(ADD_BUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(EDIT_BUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(REMOVE_BUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(VIEW_BUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(51, 51, 51))
        );

        jPanel11.setBackground(new java.awt.Color(51, 255, 255));
        jPanel11.setLayout(new javax.swing.OverlayLayout(jPanel11));

        SubjectMenu.setBackground(new java.awt.Color(0, 0, 51));

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));

        jPanel7.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Subject Details");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        EmployeeID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EmployeeID.setText("Offered Semester : ");
        EmployeeID.setToolTipText("");

        Faculty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Faculty.setText("Subject Name :");
        Faculty.setToolTipText("");

        jTextFieldID2_Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldID2_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldID2_NameActionPerformed(evt);
            }
        });

        Department.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Department.setText("Subject Code : ");
        Department.setToolTipText("");

        jTextFieldID3_Code.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldID3_Code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldID3_CodeActionPerformed(evt);
            }
        });

        Center.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Center.setText("Number Of Lecture Hours :");
        Center.setToolTipText("");

        jTextFieldID4_Lec_Hours.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldID4_Lec_Hours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldID4_Lec_HoursActionPerformed(evt);
            }
        });

        Building.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Building.setText("Number Of Tutorial Hours :");
        Building.setToolTipText("");

        jTextFieldID5_Tute_Hours.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldID5_Tute_Hours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldID5_Tute_HoursActionPerformed(evt);
            }
        });

        Level.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Level.setText("Number Of Lab Hours :");
        Level.setToolTipText("");

        jTextFieldID6_Lab_Hours.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldID6_Lab_Hours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldID6_Lab_HoursActionPerformed(evt);
            }
        });

        jTextFieldID7_Evaluation_Hours.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldID7_Evaluation_Hours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldID7_Evaluation_HoursActionPerformed(evt);
            }
        });

        Rank.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Rank.setText("Number Of Evaluation Hours :");
        Rank.setToolTipText("");

        Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Name.setText("Offered Year : ");
        Name.setToolTipText("");

        CLEARFEILDS_BUTTON.setBackground(new java.awt.Color(51, 153, 255));
        CLEARFEILDS_BUTTON.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CLEARFEILDS_BUTTON.setText("Clear Feilds");
        CLEARFEILDS_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARFEILDS_BUTTONActionPerformed(evt);
            }
        });

        jComboBox1_offered_year.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1_offered_year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Year", "Y1", "Y2", "Y3", "Y4" }));

        jComboBox2_offered_semester.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox2_offered_semester.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Semester", "S1", "S2" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CLEARFEILDS_BUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Building, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Center, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Department, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Faculty, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EmployeeID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Rank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(Level, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldID2_Name, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldID3_Code, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldID4_Lec_Hours, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldID5_Tute_Hours, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldID6_Lab_Hours)
                            .addComponent(jTextFieldID7_Evaluation_Hours)
                            .addComponent(jComboBox1_offered_year, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox2_offered_semester, javax.swing.GroupLayout.Alignment.LEADING, 0, 190, Short.MAX_VALUE))))
                .addGap(16, 16, 16))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Name, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jComboBox1_offered_year))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EmployeeID, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jComboBox2_offered_semester))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldID2_Name, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(Faculty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldID3_Code, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(Department, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldID4_Lec_Hours, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(Center, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldID5_Tute_Hours, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(Building, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldID6_Lab_Hours, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(Level, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldID7_Evaluation_Hours, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(Rank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(CLEARFEILDS_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));

        jPanel9.setBackground(new java.awt.Color(0, 0, 51));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Current Subjects");

        jTextField1_Search.setPreferredSize(new java.awt.Dimension(69, 30));

        SEARCH_BUTTON.setText("Search");
        SEARCH_BUTTON.setPreferredSize(new java.awt.Dimension(73, 30));
        SEARCH_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCH_BUTTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jTextField1_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SEARCH_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1_Search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SEARCH_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Subjects_table.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Subjects_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Offered Year", "Offered Semester", "Subject Name", "Subject Code", "No Of Lecture Hours", "No Of Tutorial Hours", "No Of Lab Hours", "No Of Evaluation Hours"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Subjects_table.setRowHeight(20);
        Subjects_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Subjects_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Subjects_table);

        REFRESH_BUTTON.setBackground(new java.awt.Color(51, 153, 255));
        REFRESH_BUTTON.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        REFRESH_BUTTON.setText("Refresh");
        REFRESH_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REFRESH_BUTTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(REFRESH_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(REFRESH_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout SubjectMenuLayout = new javax.swing.GroupLayout(SubjectMenu);
        SubjectMenu.setLayout(SubjectMenuLayout);
        SubjectMenuLayout.setHorizontalGroup(
            SubjectMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubjectMenuLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        SubjectMenuLayout.setVerticalGroup(
            SubjectMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel11.add(SubjectMenu);

        View_Subjects.setBackground(new java.awt.Color(204, 204, 255));

        jButton2.setBackground(new java.awt.Color(51, 0, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Subjects Menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel10.setBackground(new java.awt.Color(0, 0, 51));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Current Subjects");

        jTextField1_Search1.setPreferredSize(new java.awt.Dimension(69, 30));

        SEARCH_BUTTON1.setText("Search");
        SEARCH_BUTTON1.setPreferredSize(new java.awt.Dimension(73, 30));
        SEARCH_BUTTON1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCH_BUTTON1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 482, Short.MAX_VALUE)
                .addComponent(jTextField1_Search1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SEARCH_BUTTON1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1_Search1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SEARCH_BUTTON1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        REFRESH_BUTTON1.setBackground(new java.awt.Color(51, 153, 255));
        REFRESH_BUTTON1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        REFRESH_BUTTON1.setText("Refresh");
        REFRESH_BUTTON1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REFRESH_BUTTON1ActionPerformed(evt);
            }
        });

        Subjects_table1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jScrollPane2.setViewportView(Subjects_table1);

        javax.swing.GroupLayout View_SubjectsLayout = new javax.swing.GroupLayout(View_Subjects);
        View_Subjects.setLayout(View_SubjectsLayout);
        View_SubjectsLayout.setHorizontalGroup(
            View_SubjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, View_SubjectsLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(View_SubjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(View_SubjectsLayout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(REFRESH_BUTTON1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(16, 16, 16))
        );
        View_SubjectsLayout.setVerticalGroup(
            View_SubjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(View_SubjectsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 20, Short.MAX_VALUE)
                .addGroup(View_SubjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(REFRESH_BUTTON1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel11.add(View_Subjects);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ADD_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD_BUTTONActionPerformed

        Add_Subject_Form  add_subject =  new Add_Subject_Form(); 
        add_subject.setVisible(true);
        add_subject.pack();
        add_subject.setLocationRelativeTo(null);
        add_subject.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        //Add_Lecturer.setVisible(true);

    }//GEN-LAST:event_ADD_BUTTONActionPerformed

    private void REMOVE_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REMOVE_BUTTONActionPerformed
        
       if(jTextFieldID2_Name.getText().trim().equals("") || jTextFieldID3_Code.getText().trim().equals("") || jTextFieldID4_Lec_Hours.getText().trim().equals("") 
                 || jTextFieldID5_Tute_Hours.getText().trim().equals("") || jTextFieldID6_Lab_Hours.getText().trim().equals("") || jTextFieldID7_Evaluation_Hours.getText().trim().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Some Fields are empty", "Empty Field", JOptionPane.WARNING_MESSAGE);
       }
       else if(jComboBox1_offered_year.getSelectedItem().equals("Select Year") || jComboBox2_offered_semester.getSelectedItem().equals("Select Semester")){
            JOptionPane.showMessageDialog(rootPane, "Some Feilds Are Not Selected", "Fill Details Error", JOptionPane.ERROR_MESSAGE);
        }
       else{   
     // delete the selected clients
        try{
            String subject_code = String.valueOf(jTextFieldID3_Code.getText());
            String offered_year = String.valueOf(jComboBox1_offered_year.getSelectedItem());
            String offered_semester = String.valueOf(jComboBox2_offered_semester.getSelectedItem());
            String name = String.valueOf(jTextFieldID2_Name.getText());
            String lec_hours = String.valueOf(jTextFieldID4_Lec_Hours.getText());
            String tute_hours = String.valueOf(jTextFieldID5_Tute_Hours.getText());
            String lab_hours = String.valueOf(jTextFieldID6_Lab_Hours.getText());
            String evaluation_hours = String.valueOf(jTextFieldID7_Evaluation_Hours.getText());

            if(subject.removeSubject(subject_code)){
               JOptionPane.showMessageDialog(rootPane, "Subject Deleted Successfully", "Remove Subject", JOptionPane.INFORMATION_MESSAGE);  
            }else{
                JOptionPane.showMessageDialog(rootPane, "Subject Not Deleted", "Remove Subject Error", JOptionPane.ERROR_MESSAGE);
            }
         }catch(HeadlessException | NumberFormatException ex){
             
         } 
       }
        Subjects_table.setModel(new DefaultTableModel(null, new Object[]{"offered_year","offered_semester","subject_name","subject_code","no_lec_hours","no_tute_hours","no_lab_hours","no_evaluation_hours"}));
        //populate the jtable
         subject.fillSubjectJTable1(Subjects_table);
         
        Subjects_table1.setModel(new DefaultTableModel(null, new Object[]{"offered_year","offered_semester","subject_name","subject_code","no_lec_hours","no_tute_hours","no_lab_hours","no_evaluation_hours"}));
       //populate the jtable
        subject.fillSubjectJTable1(Subjects_table1);
         
        jComboBox1_offered_year.setSelectedItem("Select Year");
        jComboBox2_offered_semester.setSelectedItem("Select Semester");
        jTextFieldID2_Name.setText(" ");
        jTextFieldID3_Code.setText(" ");
        jTextFieldID4_Lec_Hours.setText(" ");
        jTextFieldID5_Tute_Hours.setText(" ");
        jTextFieldID6_Lab_Hours.setText(" ");
        jTextFieldID7_Evaluation_Hours.setText(" ");
    }//GEN-LAST:event_REMOVE_BUTTONActionPerformed

    private void EDIT_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDIT_BUTTONActionPerformed
        
        String subject_code = jTextFieldID3_Code.getText();
        String offered_year = jComboBox1_offered_year.getSelectedItem().toString();
        String offered_semester = jComboBox2_offered_semester.getSelectedItem().toString();
        String name = jTextFieldID2_Name.getText();
        String lec_hours = jTextFieldID4_Lec_Hours.getText();
        String tute_hours = jTextFieldID5_Tute_Hours.getText();
        String lab_hours = jTextFieldID6_Lab_Hours.getText();
        String evaluation_hours = jTextFieldID7_Evaluation_Hours.getText();

        if(jTextFieldID2_Name.getText().trim().equals("") || jTextFieldID3_Code.getText().trim().equals("") || jTextFieldID4_Lec_Hours.getText().trim().equals("") 
                 || jTextFieldID5_Tute_Hours.getText().trim().equals("") || jTextFieldID6_Lab_Hours.getText().trim().equals("") || jTextFieldID7_Evaluation_Hours.getText().trim().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Some Fields are empty", "Empty Field", JOptionPane.WARNING_MESSAGE);
       }
       else if(jComboBox1_offered_year.getSelectedItem().equals("Select Year") || jComboBox2_offered_semester.getSelectedItem().equals("Select Semester")){
            JOptionPane.showMessageDialog(rootPane, "Some Feilds Are Not Selected", "Fill Details Error", JOptionPane.ERROR_MESSAGE);
        }
       
        else{
            try{
                subject_code = String.valueOf(jTextFieldID3_Code.getText());

                if(subject.editSubject(subject_code,offered_year,offered_semester,name,lec_hours,tute_hours,lab_hours,evaluation_hours)){
                    JOptionPane.showMessageDialog(rootPane, "Subject Data Updated Successfully", "Edit Subject", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Subject Data Not Updated", "Edit Subject Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(rootPane, ex.getMessage() + " - Enter The Subject Code", "Subject Code Error", JOptionPane.ERROR_MESSAGE);
            }
         }  
        
       Subjects_table.setModel(new DefaultTableModel(null, new Object[]{"offered_year","offered_semester","subject_name","subject_code","no_lec_hours","no_tute_hours","no_lab_hours","no_evaluation_hours"}));
        //populate the jtable
         subject.fillSubjectJTable1(Subjects_table);
         
        Subjects_table1.setModel(new DefaultTableModel(null, new Object[]{"offered_year","offered_semester","subject_name","subject_code","no_lec_hours","no_tute_hours","no_lab_hours","no_evaluation_hours"}));
       //populate the jtable
        subject.fillSubjectJTable1(Subjects_table1);
         
        jComboBox1_offered_year.setSelectedItem("Select Year");
        jComboBox2_offered_semester.setSelectedItem("Select Semester");
        jTextFieldID2_Name.setText(" ");
        jTextFieldID3_Code.setText(" ");
        jTextFieldID4_Lec_Hours.setText(" ");
        jTextFieldID5_Tute_Hours.setText(" ");
        jTextFieldID6_Lab_Hours.setText(" ");
        jTextFieldID7_Evaluation_Hours.setText(" ");
    }//GEN-LAST:event_EDIT_BUTTONActionPerformed

    private void jTextFieldID7_Evaluation_HoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldID7_Evaluation_HoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldID7_Evaluation_HoursActionPerformed

    private void jTextFieldID6_Lab_HoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldID6_Lab_HoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldID6_Lab_HoursActionPerformed

    private void jTextFieldID5_Tute_HoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldID5_Tute_HoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldID5_Tute_HoursActionPerformed

    private void jTextFieldID4_Lec_HoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldID4_Lec_HoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldID4_Lec_HoursActionPerformed

    private void jTextFieldID3_CodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldID3_CodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldID3_CodeActionPerformed

    private void jTextFieldID2_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldID2_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldID2_NameActionPerformed

    private void REFRESH_BUTTON1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REFRESH_BUTTON1ActionPerformed
        
        Subjects_table1.setModel(new DefaultTableModel(null, new Object[]{"offered_year","offered_semester","subject_name","subject_code","no_lec_hours","no_tute_hours","no_lab_hours","no_evaluation_hours"}));
        //populate the jtable
         subject.fillSubjectJTable1(Subjects_table1);
    }//GEN-LAST:event_REFRESH_BUTTON1ActionPerformed

    private void VIEW_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VIEW_BUTTONActionPerformed
        // TODO add your handling code here:
        View_Subjects.setVisible(true);
        SubjectMenu.setVisible(false);
        // Add_Lecturer.setVisible(false);

    }//GEN-LAST:event_VIEW_BUTTONActionPerformed

    private void Subjects_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Subjects_tableMouseClicked
        
        //display the selected row data in the jtextfield
        //get the jtable model
        DefaultTableModel model = (DefaultTableModel) Subjects_table.getModel();      
        //get the selected row index
        int rIndex = Subjects_table.getSelectedRow();
        //display data
        jComboBox1_offered_year.setSelectedItem(model.getValueAt(rIndex, 0).toString());
        jComboBox2_offered_semester.setSelectedItem(model.getValueAt(rIndex, 1).toString());
        jTextFieldID2_Name.setText(model.getValueAt(rIndex, 2).toString());
        jTextFieldID3_Code.setText(model.getValueAt(rIndex, 3).toString());
        jTextFieldID4_Lec_Hours.setText(model.getValueAt(rIndex, 4).toString());
        jTextFieldID5_Tute_Hours.setText(model.getValueAt(rIndex, 5).toString());
        jTextFieldID6_Lab_Hours.setText(model.getValueAt(rIndex, 6).toString());
        jTextFieldID7_Evaluation_Hours.setText(model.getValueAt(rIndex, 7).toString());
  
    }//GEN-LAST:event_Subjects_tableMouseClicked

    private void CLEARFEILDS_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARFEILDS_BUTTONActionPerformed
        
        jComboBox1_offered_year.setSelectedItem("Select Year");
        jComboBox2_offered_semester.setSelectedItem("Select Semester");
        jTextFieldID2_Name.setText(" ");
        jTextFieldID3_Code.setText(" ");
        jTextFieldID4_Lec_Hours.setText(" ");
        jTextFieldID5_Tute_Hours.setText(" ");
        jTextFieldID6_Lab_Hours.setText(" ");
        jTextFieldID7_Evaluation_Hours.setText(" ");
    }//GEN-LAST:event_CLEARFEILDS_BUTTONActionPerformed

    private void REFRESH_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REFRESH_BUTTONActionPerformed
        
        Subjects_table.setModel(new DefaultTableModel(null, new Object[]{"offered_year","offered_semester","subject_name","subject_code","no_lec_hours","no_tute_hours","no_lab_hours","no_evaluation_hours"}));
        //populate the jtable
         subject.fillSubjectJTable1(Subjects_table);
    }//GEN-LAST:event_REFRESH_BUTTONActionPerformed

    private void SEARCH_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCH_BUTTONActionPerformed
        
        String code = jTextField1_Search.getText();
        String sql = "SELECT `offered_year`, `offered_semester`, `subject_name`, `subject_code`, `no_lec_hours`, `no_tute_hours`, `no_lab_hours`, `no_evaluation_hours` FROM `subjects` WHERE `subject_code` LIKE '%" + code + "%'";
        
        try {
            PreparedStatement pst;
            ResultSet rs;
            pst = myConnection.createConnection().prepareStatement(sql);
            rs = pst.executeQuery();
            
        Subjects_table.setModel(DbUtils.resultSetToTableModel(rs));   
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage() , "Search Details", JOptionPane.ERROR_MESSAGE);
        }
        
        jTextField1_Search.setText(" ");
    }//GEN-LAST:event_SEARCH_BUTTONActionPerformed

    private void SEARCH_BUTTON1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCH_BUTTON1ActionPerformed
        
        String code = jTextField1_Search1.getText();
        String sql = "SELECT `offered_year`, `offered_semester`, `subject_name`, `subject_code`, `no_lec_hours`, `no_tute_hours`, `no_lab_hours`, `no_evaluation_hours` FROM `subjects` WHERE `subject_code` LIKE '%" + code + "%'";
        
        try {
            PreparedStatement pst;
            ResultSet rs;
            pst = myConnection.createConnection().prepareStatement(sql);
            rs = pst.executeQuery();
            
        Subjects_table1.setModel(DbUtils.resultSetToTableModel(rs));   
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage() , "Search Details", JOptionPane.ERROR_MESSAGE);
        }
        
        jTextField1_Search1.setText(" ");
    }//GEN-LAST:event_SEARCH_BUTTON1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        HomePage home = new HomePage();
        home.setVisible(true);
        home.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         View_Subjects.setVisible(false);
        SubjectMenu.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubjectPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubjectPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubjectPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubjectPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubjectPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD_BUTTON;
    private javax.swing.JLabel Building;
    private javax.swing.JButton CLEARFEILDS_BUTTON;
    private javax.swing.JLabel Center;
    private javax.swing.JLabel Department;
    private javax.swing.JButton EDIT_BUTTON;
    private javax.swing.JLabel EmployeeID;
    private javax.swing.JLabel Faculty;
    private javax.swing.JLabel Level;
    private javax.swing.JLabel Name;
    private javax.swing.JButton REFRESH_BUTTON;
    private javax.swing.JButton REFRESH_BUTTON1;
    private javax.swing.JButton REMOVE_BUTTON;
    private javax.swing.JLabel Rank;
    private javax.swing.JButton SEARCH_BUTTON;
    private javax.swing.JButton SEARCH_BUTTON1;
    private javax.swing.JPanel SubjectMenu;
    private javax.swing.JTable Subjects_table;
    private javax.swing.JTable Subjects_table1;
    private javax.swing.JButton VIEW_BUTTON;
    private javax.swing.JPanel View_Subjects;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1_offered_year;
    private javax.swing.JComboBox jComboBox2_offered_semester;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1_Search;
    private javax.swing.JTextField jTextField1_Search1;
    private javax.swing.JTextField jTextFieldID2_Name;
    private javax.swing.JTextField jTextFieldID3_Code;
    private javax.swing.JTextField jTextFieldID4_Lec_Hours;
    private javax.swing.JTextField jTextFieldID5_Tute_Hours;
    private javax.swing.JTextField jTextFieldID6_Lab_Hours;
    private javax.swing.JTextField jTextFieldID7_Evaluation_Hours;
    // End of variables declaration//GEN-END:variables
}
