/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import dao.TagsDao;
import db.DBconnect;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class TagsPage extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1t
     */
    PreparedStatement pst;
    Connection con = null;
    ResultSet rs = null;
    
    TagsDao tags = new TagsDao();
    
    public TagsPage() {
        initComponents();
        viewTab.setBackground(Color.GRAY);
        viewFrame.setVisible(true);
        tagsFrame.setVisible(false);
        con = DBconnect.createConnection();
        
        tag_table.setModel(new DefaultTableModel(null, new Object[]{"ID","Tag Name"}));
        tags.loadAllTags(tag_table);
        
        view_tags_table.setModel(new DefaultTableModel(null, new Object[]{"ID","Tag Name"}));
        tags.loadAllTags(view_tags_table);
        
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        yearTab = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        viewTab = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        allPanels = new javax.swing.JPanel();
        viewFrame = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        view_tags_table = new javax.swing.JTable();
        view_tags_rfshBtn = new javax.swing.JButton();
        view_tags_srchTxt = new javax.swing.JTextField();
        view_tags_srchBtn = new javax.swing.JButton();
        tagsFrame = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tag_addBtn = new javax.swing.JButton();
        tag_editBtn = new javax.swing.JButton();
        tag_deleteBtn = new javax.swing.JButton();
        tag_clearBtn = new javax.swing.JButton();
        tag_add_txt = new javax.swing.JTextField();
        tagIDtxt = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        tag_tbl_srchTxt = new javax.swing.JTextField();
        tag_tbl_srchBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tag_table = new javax.swing.JTable();
        tag_tbl_rfshBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton1.setBackground(new java.awt.Color(51, 0, 51));
        jButton1.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 90, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/header_image.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 51));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel29.setFont(new java.awt.Font("Algerian", 1, 29)); // NOI18N
        jLabel29.setText("TAGS MANAGEMENT");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 81;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 577, 0, 397);
        jPanel3.add(jLabel29, gridBagConstraints);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        yearTab.setBackground(new java.awt.Color(51, 153, 255));
        yearTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yearTabMouseClicked(evt);
            }
        });
        yearTab.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel2.setText("Tags");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 29, 13, 30);
        yearTab.add(jLabel2, gridBagConstraints);

        viewTab.setBackground(new java.awt.Color(51, 153, 255));
        viewTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewTabMouseClicked(evt);
            }
        });
        viewTab.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel1.setText("View Tags");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 29, 13, 30);
        viewTab.add(jLabel1, gridBagConstraints);

        jPanel11.setBackground(new java.awt.Color(204, 204, 255));
        jPanel11.setForeground(new java.awt.Color(204, 204, 255));
        jPanel11.setLayout(new java.awt.GridBagLayout());

        jLabel28.setBackground(new java.awt.Color(204, 204, 255));
        jLabel28.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(204, 204, 255));
        jLabel28.setText("Year & Semester");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 29, 13, 30);
        jPanel11.add(jLabel28, gridBagConstraints);

        jPanel27.setBackground(new java.awt.Color(204, 204, 255));
        jPanel27.setForeground(new java.awt.Color(204, 204, 255));
        jPanel27.setLayout(new java.awt.GridBagLayout());

        jLabel31.setBackground(new java.awt.Color(204, 204, 255));
        jLabel31.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(204, 204, 255));
        jLabel31.setText("tag");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 109, 13, 109);
        jPanel27.add(jLabel31, gridBagConstraints);

        jPanel28.setBackground(new java.awt.Color(204, 204, 255));
        jPanel28.setForeground(new java.awt.Color(204, 204, 255));
        jPanel28.setLayout(new java.awt.GridBagLayout());

        jLabel32.setBackground(new java.awt.Color(204, 204, 255));
        jLabel32.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(204, 204, 255));
        jLabel32.setText("tag");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 109, 13, 109);
        jPanel28.add(jLabel32, gridBagConstraints);

        jPanel29.setBackground(new java.awt.Color(204, 204, 255));
        jPanel29.setForeground(new java.awt.Color(204, 204, 255));
        jPanel29.setLayout(new java.awt.GridBagLayout());

        jLabel33.setBackground(new java.awt.Color(204, 204, 255));
        jLabel33.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(204, 204, 255));
        jLabel33.setText("tag");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 109, 13, 109);
        jPanel29.add(jLabel33, gridBagConstraints);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yearTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(yearTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        allPanels.setBackground(new java.awt.Color(51, 255, 255));
        allPanels.setLayout(new javax.swing.OverlayLayout(allPanels));

        viewFrame.setBackground(new java.awt.Color(204, 204, 255));

        jPanel5.setBackground(new java.awt.Color(0, 0, 51));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tags Details");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 361, 0, 462);
        jPanel5.add(jLabel7, gridBagConstraints);

        view_tags_table.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        view_tags_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        view_tags_table.setRowHeight(28);
        jScrollPane2.setViewportView(view_tags_table);

        view_tags_rfshBtn.setBackground(new java.awt.Color(51, 153, 255));
        view_tags_rfshBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        view_tags_rfshBtn.setText("REFRESH");
        view_tags_rfshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_tags_rfshBtnActionPerformed(evt);
            }
        });

        view_tags_srchTxt.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N

        view_tags_srchBtn.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        view_tags_srchBtn.setText("SEARCH");
        view_tags_srchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_tags_srchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewFrameLayout = new javax.swing.GroupLayout(viewFrame);
        viewFrame.setLayout(viewFrameLayout);
        viewFrameLayout.setHorizontalGroup(
            viewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 1006, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewFrameLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(view_tags_srchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(view_tags_srchBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewFrameLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(view_tags_rfshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        viewFrameLayout.setVerticalGroup(
            viewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewFrameLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(viewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(view_tags_srchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(view_tags_srchBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addGap(35, 35, 35)
                .addComponent(view_tags_rfshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        allPanels.add(viewFrame);

        tagsFrame.setBackground(new java.awt.Color(0, 0, 51));

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));

        jPanel8.setBackground(new java.awt.Color(0, 0, 51));
        jPanel8.setLayout(new java.awt.GridBagLayout());

        jLabel8.setFont(new java.awt.Font("Sitka Text", 3, 28)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tags");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 36, 0, 43);
        jPanel8.add(jLabel8, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Sitka Text", 1, 20)); // NOI18N
        jLabel10.setText("Tag");

        tag_addBtn.setBackground(new java.awt.Color(51, 153, 255));
        tag_addBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tag_addBtn.setText("ADD");
        tag_addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tag_addBtnActionPerformed(evt);
            }
        });

        tag_editBtn.setBackground(new java.awt.Color(51, 153, 255));
        tag_editBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tag_editBtn.setText("EDIT");
        tag_editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tag_editBtnActionPerformed(evt);
            }
        });

        tag_deleteBtn.setBackground(new java.awt.Color(51, 153, 255));
        tag_deleteBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tag_deleteBtn.setText("DELETE");
        tag_deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tag_deleteBtnActionPerformed(evt);
            }
        });

        tag_clearBtn.setBackground(new java.awt.Color(51, 153, 255));
        tag_clearBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tag_clearBtn.setText("CLEAR");
        tag_clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tag_clearBtnActionPerformed(evt);
            }
        });

        tag_add_txt.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tag_deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tag_editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tag_addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tag_clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tag_add_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tagIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tagIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tag_add_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(78, 78, 78)
                .addComponent(tag_addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(tag_editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(tag_deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tag_clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(204, 204, 255));

        jPanel9.setBackground(new java.awt.Color(0, 0, 51));

        jLabel9.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tags Details");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(484, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tag_tbl_srchTxt.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N

        tag_tbl_srchBtn.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        tag_tbl_srchBtn.setText("SEARCH");
        tag_tbl_srchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tag_tbl_srchBtnActionPerformed(evt);
            }
        });

        tag_table.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tag_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tag_table.setRowHeight(28);
        tag_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tag_tableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tag_table);

        tag_tbl_rfshBtn.setBackground(new java.awt.Color(51, 153, 255));
        tag_tbl_rfshBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tag_tbl_rfshBtn.setText("REFRESH");
        tag_tbl_rfshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tag_tbl_rfshBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tag_tbl_srchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tag_tbl_srchBtn))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tag_tbl_rfshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tag_tbl_srchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tag_tbl_srchBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(tag_tbl_rfshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout tagsFrameLayout = new javax.swing.GroupLayout(tagsFrame);
        tagsFrame.setLayout(tagsFrameLayout);
        tagsFrameLayout.setHorizontalGroup(
            tagsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tagsFrameLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tagsFrameLayout.setVerticalGroup(
            tagsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        allPanels.add(tagsFrame);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(allPanels, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(allPanels, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewTabMouseClicked
        // TODO add your handling code here:
        viewFrame.setVisible(true);
        tagsFrame.setVisible(false);
        
        viewTab.setBackground(Color.GRAY);
        yearTab.setBackground(new Color(51,153,255));
        
    }//GEN-LAST:event_viewTabMouseClicked

    private void yearTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yearTabMouseClicked
        // TODO add your handling code here:
        viewFrame.setVisible(false);
        tagsFrame.setVisible(true);
        
        viewTab.setBackground(new Color(51,153,255));
        yearTab.setBackground(Color.GRAY);
    }//GEN-LAST:event_yearTabMouseClicked

    private void view_tags_rfshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_tags_rfshBtnActionPerformed
        // TODO add your handling code here:
        view_tags_table.setModel(new DefaultTableModel(null, new Object[]{"ID","Tag Name"}));
        tags.loadAllTags(view_tags_table);
        view_tags_srchTxt.setText("");
    }//GEN-LAST:event_view_tags_rfshBtnActionPerformed

    private void tag_addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tag_addBtnActionPerformed
        // TODO add your handling code here:
        if(tag_add_txt.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Input Field is Empty", "Fill Details Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            int x = JOptionPane.showConfirmDialog(null, "Do You Want To Add this Tag ?");
            
            if(x == 0){
                String tag = tag_add_txt.getText();
                
                try {
                    if(tags.addTag(tag)){
                    JOptionPane.showMessageDialog(rootPane, "Tag Added Successfully", "Add Tag", JOptionPane.INFORMATION_MESSAGE);
                    }
                    else{
                        JOptionPane.showMessageDialog(rootPane, "Already exists or inavid data. Please check...", "Fill Details Error", JOptionPane.ERROR_MESSAGE);
                    }  
                } 
                catch (HeadlessException e) {
                    System.out.println(e);
                }
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Data Not Inserted", "Add Tag", JOptionPane.WARNING_MESSAGE);
            }
            
        }
        
        tagIDtxt.setText("");
        tag_add_txt.setText("");
              
        tag_table.setModel(new DefaultTableModel(null, new Object[]{"ID","Tag Name"}));
        tags.loadAllTags(tag_table);
    }//GEN-LAST:event_tag_addBtnActionPerformed

    private void tag_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tag_tableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tag_table.getModel();      
        
        int rIndex = tag_table.getSelectedRow();
        tagIDtxt.setText(model.getValueAt(rIndex, 0).toString());
        tag_add_txt.setText(model.getValueAt(rIndex, 1).toString());
    }//GEN-LAST:event_tag_tableMouseClicked

    private void tag_editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tag_editBtnActionPerformed
        // TODO add your handling code here:
        if(tag_add_txt.getText().equals("") || tagIDtxt.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Please select row in the table OR Invalid Data", "Edit Details Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            int x = JOptionPane.showConfirmDialog(null, "Do You Want To Edit this Tag ?");
            
            if(x == 0){
                int id = Integer.valueOf(tagIDtxt.getText());
                String tag = tag_add_txt.getText();
                
                try {
                    if(tags.editTag(id,tag)){
                    JOptionPane.showMessageDialog(rootPane, "Tag Edit Successfully", "Edit Tag", JOptionPane.INFORMATION_MESSAGE);
                    }
                    else{
                        JOptionPane.showMessageDialog(rootPane, "Already exists or inavid data. Please check...", "Edit Details Error", JOptionPane.ERROR_MESSAGE);
                    }  
                } 
                catch (HeadlessException e) {
                    System.out.println(e);
                }
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Data Not Updated", "Edit Tag", JOptionPane.WARNING_MESSAGE);
            }
            
        }
        
        tagIDtxt.setText("");
        tag_add_txt.setText("");
              
        tag_table.setModel(new DefaultTableModel(null, new Object[]{"ID","Tag Name"}));
        tags.loadAllTags(tag_table);
    }//GEN-LAST:event_tag_editBtnActionPerformed

    private void tag_deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tag_deleteBtnActionPerformed
        // TODO add your handling code here:
        if(tag_add_txt.getText().equals("") || tagIDtxt.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Please select row in the table OR Invalid Data", "Delete Details Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            int x = JOptionPane.showConfirmDialog(null, "Do You Want To Delete this Tag ?");
            
            if(x == 0){
                int id = Integer.valueOf(tagIDtxt.getText());               
                try {
                    if(tags.deleteTag(id)){
                    JOptionPane.showMessageDialog(rootPane, "Tag Delete Successfully", "Delete Tag", JOptionPane.INFORMATION_MESSAGE);
                    }
                    else{
                        JOptionPane.showMessageDialog(rootPane, "Already exists or inavid data. Please check...", "Delete Details Error", JOptionPane.ERROR_MESSAGE);
                    }  
                } catch (Exception e) {
                    System.out.println(e);
                }
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Data Not Deleted", "Delete Tag", JOptionPane.WARNING_MESSAGE);
            }
            
        }
        tagIDtxt.setText("");
        tag_add_txt.setText("");
              
        tag_table.setModel(new DefaultTableModel(null, new Object[]{"ID","Tag Name"}));
        tags.loadAllTags(tag_table);
    }//GEN-LAST:event_tag_deleteBtnActionPerformed

    private void tag_clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tag_clearBtnActionPerformed
        // TODO add your handling code here:
        tagIDtxt.setText("");
        tag_add_txt.setText("");
    }//GEN-LAST:event_tag_clearBtnActionPerformed

    private void tag_tbl_srchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tag_tbl_srchBtnActionPerformed
        // TODO add your handling code here:
        try {
            String tag = tag_tbl_srchTxt.getText();
            tag_table.setModel(new DefaultTableModel(null, new Object[]{"ID","Tag Name"}));
            tags.searchTag(tag_table,tag);
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_tag_tbl_srchBtnActionPerformed

    private void tag_tbl_rfshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tag_tbl_rfshBtnActionPerformed
        // TODO add your handling code here:
        tag_table.setModel(new DefaultTableModel(null, new Object[]{"ID","Tag Name"}));
        tags.loadAllTags(tag_table);
        tag_tbl_srchTxt.setText("");
    }//GEN-LAST:event_tag_tbl_rfshBtnActionPerformed

    private void view_tags_srchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_tags_srchBtnActionPerformed
        // TODO add your handling code here:
        try {
            String tag = view_tags_srchTxt.getText();
            view_tags_table.setModel(new DefaultTableModel(null, new Object[]{"ID","Tag Name"}));
            tags.searchTag(view_tags_table,tag);
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_view_tags_srchBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        HomePage homePage = new HomePage();
        homePage.setVisible(true);
        homePage.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TagsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TagsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TagsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TagsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TagsPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel allPanels;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel tagIDtxt;
    private javax.swing.JButton tag_addBtn;
    private javax.swing.JTextField tag_add_txt;
    private javax.swing.JButton tag_clearBtn;
    private javax.swing.JButton tag_deleteBtn;
    private javax.swing.JButton tag_editBtn;
    private javax.swing.JTable tag_table;
    private javax.swing.JButton tag_tbl_rfshBtn;
    private javax.swing.JButton tag_tbl_srchBtn;
    private javax.swing.JTextField tag_tbl_srchTxt;
    private javax.swing.JPanel tagsFrame;
    private javax.swing.JPanel viewFrame;
    private javax.swing.JPanel viewTab;
    private javax.swing.JButton view_tags_rfshBtn;
    private javax.swing.JButton view_tags_srchBtn;
    private javax.swing.JTextField view_tags_srchTxt;
    private javax.swing.JTable view_tags_table;
    private javax.swing.JPanel yearTab;
    // End of variables declaration//GEN-END:variables
}
